services:
  - type: web
    name: food-availability-checker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: ""gunicorn -w 4 -b 0.0.0.0:5000 app:app""
    repo: https://github.com/RajNadkarni/DHScraper
