services:
  - type: web
    name: food-availability-checker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    repo: https://github.com/RajNadkarni/DHScraper
